### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by GregTexas** [bryansh/lendingClubAPI#2]
Hello,

I'm new to Node or really any Java. I'm testing using https://tonicdev.com/npm/node-lending-club-api
and I get the error ReferenceError: cb is not defined. From using the line "lc.accounts.availableCash(MyAccoun#, cb)" What is cb? I get the same error for all the commands.

Thanks

**Comment by bryansh** [comment]
Sorry for the delay here, I must have missed the notifications!  😢 

cb stands for callback, and is the vehicle for the api giving you the information that you requested.  For example:

`lc.accounts.availableCash(MyAccount#, function(err, data) {
console.log(data.availableCash);
});`

Is the anticipated usage.
